spring:
  profiles:
    active: @spring.profile.activated@
  datasource:
    url: jdbc:mysql://192.168.101.200:3306/sakila?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 20
  cloud:
    stream:
      function:
        definition: sink;transfer;gather
      bindings:
        output:
          destination: test1
        transfer-in-0:
          destination: test1
          group: transfer
        transfer-out-0:
          destination: test2
        sink-in-0:
          destination: test2
          group: sink
        gather1:
          destination: input1
        gather2:
          destination: input2
        gather-in-0:
          destination: input1
          group: gather1
        gather-in-1:
          destination: input2
          group: gather2
        gather-out-0:
          destination: test2
      kafka:
        binder:
          brokers: 192.168.101.200:9092
  redis:
    redisson:
      file: classpath:redisson.yaml
redis:
  host: 192.168.101.200
  port: 6379
  database: 0
  timeout: 3000
  connection:
    poolSize: 32
    minimumIdle-size: 10